---
title: "Assignment4"
author: "Haojin Li (Declan)"
date: "2020/7/25"
output: pdf_document
toc: true
---

# Initiation
```{r}
library(ISLR)
library(class)

data("Smarket")
```



# 4.6.1 The Stock Market Data
```{r}
summary(Smarket)
names(Smarket)
dim(Smarket)
pairs(Smarket)
```
```{r}
cor(Smarket [,-9])
```
```{r}
attach(Smarket)
plot(Volume)
```

# 4.6.2 Logistic Regression

```{r}
glm.fits=glm(Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume ,data=Smarket ,family=binomial )
summary(glm.fits)
coef(glm.fits)
summary (glm.fits)$coef
```

```{r}
glm.probs=predict (glm.fits,type="response")
glm.probs[1:10]
contrasts (Direction)
```

```{r}
glm.pred=rep("Down" ,1250)
glm.pred[glm.probs >.5]="Up"
table(glm.pred ,Direction)
mean(glm.pred==Direction)
```

```{r}
train=(Year<2005)
Smarket.2005 <- Smarket [!train ,]
dim(Smarket.2005)
Direction.2005= Direction [!train]
```

```{r}
glm.fits=glm(Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume ,data=Smarket ,family=binomial ,subset=train)
glm.probs=predict(glm.fits,Smarket.2005, type="response")
```

```{r}
glm.pred=rep("Down",252)
glm.pred[glm.probs >.5]="Up"
table(glm.pred ,Direction.2005)
mean(glm.pred==Direction.2005)
mean(glm.pred!=Direction.2005)

```
```{r}
glm.fits <- glm(Direction ~ Lag1+Lag2, data=Smarket, family=binomial, subset=train)
glm.probs <- predict(glm.fits, Smarket.2005, type="response")
glm.pred <- rep("Down", 252)
table(glm.pred, Direction.2005)
mean(glm.pred == Direction.2005)
```
```{r}
predict(glm.fits,newdata =data.frame(Lag1=c(1.2 ,1.5),Lag2=c(1.1,-0.8) ),type="response")
```

# 4.6.5 K-Nearest Neighbors

```{r}
train.X=cbind(Lag1 ,Lag2)[train ,]
test.X=cbind(Lag1 ,Lag2)[!train ,]
train.Direction =Direction [train]
```

```{r}
set.seed(7)
knn.pred=knn(train.X,test.X,train.Direction ,k=1)
table(knn.pred ,Direction.2005)
```

```{r}
knn.pred=knn(train.X,test.X,train.Direction ,k=3)
table(knn.pred ,Direction.2005)
mean(knn.pred==Direction.2005)
```

